# General
BUILDINGS = 'buildings'
UNITS = 'units'
RESEARCH = 'tech'
AGE_UP_TIMES = 'age_up_times'
CIV = 'civilization'
PLAYER_ID = 'player_id'
BUILDING_ID = 'building_id'
TECHNOLOGY_ID = 'technology_id'
UNIT_ID = 'unit_id'

# Buildings
ID_HOUSE = 70
ID_BARRACKS = 12
ID_STABLE = 101
ID_RANGE = 87
ID_MILL = 68
ID_BLACKSMITH = 103
ID_MARKET = 84
ID_CASTLE = 82
ID_DOCK = 45
ID_TC = 621
ID_TOWER = 79

# Technology
ID_LOOM = 22
ID_WHEELBARROW = 213
ID_TOWN_WATCH = 8
ID_DOUBLE_BIT_AXE = 202
ID_HORSE_COLLAR = 14
ID_FEUDAL_AGE = 101
ID_CASTLE_AGE = 102
ID_IMPERIAL_AGE = 103
ID_MAN_AT_ARMS_UPGRADE = 222

# Units
ID_MILITA = 74
ID_ARCHER = 4
ID_SKIRMISHER = 7
ID_SCOUT = 448
ID_KNIGHT = 38
ID_EAGLE = 751
ID_BATTLE_ELEPHANT = 1132
ID_CAMEL = 329
ID_VILLAGER_MALE = 83
ID_VILLAGER_FEMALE = 293